### ISSUE TITLE
Poster Discussion

### ISSUE THREAD

**Issue by mkhattab940** [hakaru-CS4ZP6/hakaru#32]
Latest poster can be found in the following repo:
https://github.com/hakaru-CS4ZP6/Hakaru-Poster/tree/master

@staplejw can you push up the latest compiled poster.pdf before assigning Dr. Carette to this issue?

**Comment by staplejw** [comment]
I have pushed the latest pdf version of the poster. I am curious to hear everyones thoughts and critiques. Compared to a lot of the other posters that I have seen from groups in our class, we have a lot of text. This is becoming a problem because we are running out of room on the poster yet still have things to add. @maymoo99  and I were talking about removing the section on implementing distributions via PDF/PMF. However, this is the section that contains Hakaru code, and I think it is important to have some Hakaru code somewhere on the poster. Ideas on where else that could be included?

**Comment by mkhattab940** [comment]
TBH, that hakaru code in particular isn't great since it isn't representative of the majority of the code we're writing anyways. Needing to resort to PDF/PMF is a border-line fringe case when it comes to stdlib development and it is irrelevant to test case writing. So, yeah, I think it's fine to nuke the whole section and save that information for the paper where more in-depth discussion is warranted.

I think instead we should show 2 example distribution implementations one of each form discussed, maybe tuck them under the formal transformation definition. Also, let's use screenshots directly from sublime to show off the syntax-highlighting.

In the meantime I'll branch off and start paring down the rest of the text.

**Comment by JacquesCarette** [comment]
Yeah, way too many words. Sometimes you can just be more succinct by rephrasing. And, on posters, you frequently don't need complete sentences.  And you want to illustrate things with more visual items -- pictures, code, diagrams, etc. You do have some nice ones, you should strive for more.

**Comment by JacquesCarette** [comment]
I'm going to email 2 sample posters to give you an idea.

**Comment by JacquesCarette** [comment]
Ok, I've emailed them to Justin, as I don't seem to have anyone else's email!!

**Comment by mkhattab940** [comment]
Suggestion for another picture to include: we could show the histrogram script results next to the PDF curves for a distribution that can take on a wide range of shapes depending on its parameters. Show 3 in a row in single figure. Talk a bit about how we used it to visually verify stdlib correctness.

**Comment by staplejw** [comment]
@maymoo99 I have addressed some of the comments that you made in your most recent commit to the poster repo. Here are my thoughts on each section:

- Introduction: I have transformed that content into bullet points. I find the use of the rightarrow (=>) and equivs (==) awkward when they are mixed in with words. Can you think of another symbol to use or another simple way to put this? 

- Key Concepts: I have reformatted the info about ~ and <~ as you had originally intended. Again, I find the == awkward and I am wondering if we can write this in another way. TODO: change the section to blue and put a box around it. try to remove annoying space between 2nd and 3rd star. 

- Motivation: I didn't make any changes to this section yet. I am thinking that we just keep this section simple. Increase the text size and give brief explanations for each of the objectives and endeavours that are listed. 

- Standard Library Development: What is your intention with the PHILOSOPHY heading? Would you like this to become its own section? Following the sentence "For example, the standard chi-square distribution is defined as the sum of the squares of n standard normal random variables" I think it would good to show a sublime screenshot of our own chi-square implementation in hakaru. the chi-square is very relevant to our development and gives us another opportunity to show off the syntax highlighting and add another picture/figure (we could then add "see figure 3" at the end of the sentence above). Thoughts on whether we would like to give an example of an implementation of a discrete distribution and if so, which one?

- Test Relationships Between Distributions: This section is incomplete. I think we had been talking about including an example of one of our tests. Perhaps we would show an example 0.hk/expected.hk pairing and also give the mathematical description of the transformation in another box? Thoughts on this? (EDIT: I am wondering if it might be worth chopping some text in this section. Perhaps we could describe our hypothesis in fewer words, or give a less complete, less formal desription).

- Conclusions and Future Work: This section is still completely open. Given the nature of Hakaru as a research endeavour, there is much to say about potential future work. More tests (sooo many), more language features (primitives, error handling, importing?), multivariate distributions, etc. Would anybody like to this claim this section? @NevinM14 ? @sohraa3 ?

- References: These will fall into place once we have all the content in.

**Comment by mkhattab940** [comment]
@staplejw 

- Intro: You could change the => to "means" or something. 
- Key Concepts: How about \equiv? If you still feel awkward I leave it to your discretion
- Motivation: Could you make the subpoints list vertically under a CAPTILIZED heading? Like how it is in Key Concepts.
- Standard Library Development: Let's replace that heading with a short paragraph that leads into the bullet points. I'll take care of that. Again, list them vertically. Screenshot of chiSq implementation sounds good. For the discrete one, let's do gammaPoisson since it is also an example of Bayesian inference, which is the second relation type discussed.
- Testing: Yaaah, gonna need more time for this. I think we've still got quite a bit to wrap our heads around when it comes to testing to worry about filling in this part just yet.

**Comment by sohraa3** [comment]
@maymoo99 @staplejw 
I have made some modifications on the poster but before going further, I wanted to discuss the following points with you.

- To reduce the content we can remove the section on probability distributions and assume that the reader is familiar with those concepts. The sample posters given by Dr.Carrete don't include mathematical background info, so we can remove that part if you want.
- I don't think the use of "==" is good either.
- I am not sure if hk-maple is an inference algorithm(first column befor key concepts). I think disintegrate is used for inferences. We used hk-maple for simplifications.
- I think we can divide the intro section into smaller pieces. Right now there are many different information on it. My idea is to divide it into three sections: 1-Introduction 2-Mathematical background(if we plan on keeping this) 3-Language guide( some of the stuff from key concepts fit here)
- We can change the "key concepts" title to "terminology". I think that makes more sense.
- should we talk about our implementations of choose and log?
- not sure about the second formula in the bottom of second coloumn C(p,q)=Y~B(q,X). shouldn't it be C(p,q)= B(q,X) (without Y)?
- we can make two sub heading in Standard Library Development section. one for implementation using transformations and another for implementation from PDFs/PMFs which can be divided further to categorical and weight. I think we should keep the latter section btw because it was a great portion of the distributions.
- Testing: I was wondering if we could talk about histogram.py in this section. I know it is not a rigorous method but it is good for quickly telling if something is off.

**Comment by mkhattab940** [comment]
@sohraa3 
I disagree about not including an intro about statistics. Those are grad level projects and we're undergrads and we have to keep in mind the difference of our audience

hk-maple is an inference algorithm according to the front page of the documentation: http://hakaru-dev.github.io/#transformations

I like the idea of splitting up the intro. You want to tackle that?

You're right about the second formula being wrong, but we definitely need Y. @staplejw it should be: X ~ dist_A(p) => Y ~ dist_B(q,X) = dist_C(p,q)

**Comment by staplejw** [comment]
I made a bunch of changes. 

- Intro: changed symbol to words
- Key Concepts: changed symbols
- Motivation: Reformatted this section according to @maymoo99 's intentions. 
- Standard Library Development: I created those new bullets. I added two new figures that show Hakaru code for chi-square and gamma-poisson. I also fixed the equation like you mentioned. 

This code was pushed on mahmoud's branch. @sohraa3 I don't think the section on implementing the distributions via PDF/PMF is that important. Our poster already has a ton of content and we can afford to cut some. I feel that the intro is important because it makes our project more accessible and that is largely what we are being evaluated on.

**Comment by JacquesCarette** [comment]
When is this due?  What exactly do you expect me to do on this, by when?

**Comment by christopheranand** [comment]
It is past due, but without penalty. 


The TAs and I have been giving extensive comments, and other groups have made several iterations. But they need to present it to graduate!

Sent from my iPhone

On Mar 29, 2018, at 1:28 PM, Jacques Carette <notifications@github.com> wrote:




When is this due? What exactly do you expect me to do on this, by when?
—
You are receiving this because you were assigned.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by staplejw** [comment]
We have planned on having a draft done by the end of the day today so that we can submit it to the TA's and Dr. Anand for critiques. @JacquesCarette, could you also provide some brief critiques? Preferably by the end of tomorrow?

**Comment by JacquesCarette** [comment]
Feedback: the content and organization of the poster is very good. What was chosen to be shown is very representative of the work being done.

The poster itself could be improved by having a lot fewer words (and more pictures / code / etc) to communicate the same content.

**Comment by JacquesCarette** [comment]
@staplejw in #39 mentions "With the poster out of the way".  Does that mean it is time to close this issue?

**Comment by staplejw** [comment]
Yes, this is a very recent development.
